version: '3.1'
services:
  demo-frog-app:
    container_name: frog-app
    image: demo-frog
#    build: ./
    ports:
      - '8081:8081'
    depends_on:
      - demo-api-db
  demo-api-db:
    image: 'postgres:15'
    container_name: 'java-pg'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
#      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=mydb'
