spring:
  application:
    name: demo-frog
    sql:
      init:
        mode=always
    ports:
      - 8081:8081
  jpa:
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto=create
  datasource:
    url: jdbc:postgresql://demo-api-db:5432/mydb
    username: admin
    password: admin
